import Link from "next/link";
import { notFound } from "next/navigation";
import { Container } from "@/components/ui/container";
import { createClient } from "@/lib/supabase/server";
import { trustLabels, type CommunityPlace } from "@/lib/day3/types";
import { confirmPlace, recommendPlace, reportPlace, submitCorrection, submitReview } from "../actions";

export const dynamic = "force-dynamic";

export default async function PlacePage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ success?: string; error?: string }> }) {
  const { id } = await params;
  const status = await searchParams;
  const supabase = await createClient();
  const { data } = await supabase.from("community_places").select("id,name,description,address_text,city,state_region,latitude,longitude,phone,website_url,trust_label,category:place_categories(id,name,slug)").eq("id", id).eq("moderation_status", "approved").single();
  if (!data) notFound();
  const place = data as unknown as CommunityPlace;
  const { data: reviews } = await supabase.from("place_reviews").select("id,rating,review_text,created_at").eq("place_id", id).eq("moderation_status", "approved").order("created_at", { ascending: false });
  return <main className="flex-1 py-12"><Container><div className="mx-auto max-w-3xl">
    <Link href="/map" className="text-sm font-semibold text-brand-700">← Kembali ke DUTA Map</Link><div className="mt-5 rounded-2xl border border-slate-200 bg-white p-7 shadow-sm"><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-900">{trustLabels[place.trust_label]}</span><h1 className="mt-4 text-3xl font-bold">{place.name}</h1><p className="mt-2 font-semibold text-brand-700">{place.category?.name}</p>{place.description && <p className="mt-4 leading-7 text-slate-600">{place.description}</p>}<dl className="mt-6 grid gap-4"><Info label="Alamat" value={`${place.address_text}, ${place.city}, ${place.state_region}`} /><Info label="Telepon" value={place.phone ?? "Tidak tersedia"} /></dl>{place.website_url && <Link href={place.website_url} target="_blank" rel="noreferrer" className="mt-5 inline-flex font-semibold text-brand-700 hover:underline">Buka website</Link>}<p className="mt-6 rounded-lg bg-amber-50 p-4 text-sm text-amber-900">Informasi ini berasal dari komunitas, bukan data resmi pemerintah. Periksa kembali sebelum mengandalkannya.</p></div>
    {status.success && <p className="mt-5 rounded-lg bg-emerald-50 p-4 text-emerald-900">Kontribusi diterima. Item yang memerlukan moderasi belum langsung dipublikasikan.</p>}{status.error && <p className="mt-5 rounded-lg bg-red-50 p-4 text-red-900">Kontribusi belum berhasil. Pastikan Anda sudah masuk dan isian valid.</p>}
    <div className="mt-8 grid gap-5 sm:grid-cols-2"><SimpleAction title="Rekomendasikan tempat" action={recommendPlace} id={id} button="Rekomendasikan" /><SimpleAction title="Konfirmasi informasi" action={confirmPlace} id={id} button="Saya mengonfirmasi" /></div>
    <Contribution title="Sarankan koreksi" action={submitCorrection}><input type="hidden" name="placeId" value={id} /><label className="text-sm font-semibold">Bagian yang dikoreksi<select name="field" className="mt-2 min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3"><option value="name">Nama</option><option value="description">Deskripsi</option><option value="address_text">Alamat</option><option value="city">Kota</option><option value="state_region">Negeri/wilayah</option><option value="phone">Telepon</option><option value="website_url">Website</option></select></label><Text name="proposedValue" label="Nilai yang benar" /><Text name="reason" label="Alasan dan sumber pengetahuan Anda" area /></Contribution>
    <Contribution title="Tulis ulasan" action={submitReview}><input type="hidden" name="placeId" value={id} /><label className="text-sm font-semibold">Penilaian<select name="rating" className="mt-2 min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3">{[5,4,3,2,1].map((n) => <option key={n} value={n}>{n} bintang</option>)}</select></label><Text name="reviewText" label="Ulasan" area /></Contribution>
    <Contribution title="Laporkan informasi tidak akurat" action={reportPlace}><input type="hidden" name="placeId" value={id} /><label className="text-sm font-semibold">Alasan<select name="reportReason" className="mt-2 min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3"><option value="incorrect_information">Informasi salah</option><option value="closed">Sudah tutup</option><option value="duplicate">Duplikat</option><option value="unsafe">Masalah keselamatan</option><option value="other">Lainnya</option></select></label><Text name="details" label="Detail laporan" area /></Contribution>
    <section className="mt-8"><h2 className="text-2xl font-bold">Ulasan yang disetujui</h2><div className="mt-4 space-y-4">{reviews?.map((r) => <article key={r.id} className="rounded-xl border border-slate-200 bg-white p-5"><p className="font-semibold">{r.rating}/5</p><p className="mt-2 text-slate-600">{r.review_text}</p></article>)}{!reviews?.length && <p className="text-slate-600">Belum ada ulasan yang disetujui.</p>}</div></section>
  </div></Container></main>;
}

function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-sm font-semibold text-slate-500">{label}</dt><dd className="mt-1 text-slate-800">{value}</dd></div>; }
function SimpleAction({ title, action, id, button }: { title: string; action: (data: FormData) => Promise<void>; id: string; button: string }) { return <form action={action} className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-bold">{title}</h2><input type="hidden" name="placeId" value={id} /><button className="mt-4 min-h-10 rounded-lg bg-brand-700 px-4 font-semibold text-white">{button}</button></form>; }
function Contribution({ title, action, children }: { title: string; action: (data: FormData) => Promise<void>; children: React.ReactNode }) { return <form action={action} className="mt-8 space-y-4 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">{title}</h2>{children}<button className="min-h-11 rounded-lg bg-slate-900 px-5 font-semibold text-white">Kirim</button></form>; }
function Text({ name, label, area = false }: { name: string; label: string; area?: boolean }) { return <label className="block text-sm font-semibold">{label}{area ? <textarea name={name} required minLength={10} rows={4} className="mt-2 w-full rounded-lg border border-slate-300 p-3" /> : <input name={name} required className="mt-2 min-h-11 w-full rounded-lg border border-slate-300 px-3" />}</label>; }
