import { Container } from "@/components/ui/container";
import { createClient } from "@/lib/supabase/server";
import { moderateJob, registerExternalSource, verifyEmployer } from "./actions";

export default async function CareerAdminPage() {
  const supabase = await createClient();
  const [{ data: employers }, { data: jobs }, { data: sources }] = await Promise.all([
    supabase.from("employers").select("id,name,country_code,status,created_at").eq("status", "pending").order("created_at"),
    supabase.from("jobs").select("id,title,source_type,status,created_at").eq("status", "pending").order("created_at"),
    supabase.from("external_job_sources").select("id,code,name,official_url,authorization_status,is_active"),
  ]);
  return <main className="flex-1 py-12"><Container><p className="text-sm font-semibold uppercase text-brand-700">Admin DUTA KARIER</p><h1 className="mt-3 text-4xl font-bold">Verifikasi dan moderasi</h1><div className="mt-8 grid gap-8 lg:grid-cols-2"><section><h2 className="text-2xl font-bold">Pemberi kerja menunggu</h2><div className="mt-4 grid gap-4">{employers?.map((employer) => <form action={verifyEmployer} key={employer.id} className="rounded-2xl border bg-white p-5"><input type="hidden" name="employerId" value={employer.id}/><strong>{employer.name}</strong><p className="mt-1 text-sm">{employer.country_code}</p><input name="sourceUrl" type="url" required placeholder="URL sumber resmi HTTPS" className="mt-4 min-h-11 w-full rounded-lg border px-3"/><button className="mt-3 min-h-11 w-full rounded-lg bg-brand-700 font-semibold text-white">Verifikasi dengan sumber</button></form>)}{!employers?.length && <p>Tidak ada antrean.</p>}</div></section><section><h2 className="text-2xl font-bold">Lowongan menunggu</h2><div className="mt-4 grid gap-4">{jobs?.map((job) => <form action={moderateJob} key={job.id} className="rounded-2xl border bg-white p-5"><input type="hidden" name="jobId" value={job.id}/><strong>{job.title}</strong><p className="text-sm text-slate-600">{job.source_type}</p><div className="mt-3 flex gap-2"><button name="status" value="published" className="rounded-lg bg-brand-700 px-4 py-2 font-semibold text-white">Publikasikan</button><button name="status" value="rejected" className="rounded-lg border px-4 py-2 font-semibold">Tolak</button></div></form>)}{!jobs?.length && <p>Tidak ada antrean.</p>}</div></section></div><section className="mt-10 max-w-3xl rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">Sumber lowongan eksternal</h2><p className="mt-2 text-sm text-slate-600">Arsitektur SISKOP2MI tersedia tetapi adaptor tetap nonaktif sampai tersedia feed/API resmi dan izin penggunaan. Scraping tidak digunakan.</p><div className="mt-4 grid gap-2">{sources?.map((source) => <div key={source.id} className="rounded-lg bg-slate-50 p-3"><strong>{source.name}</strong><p className="text-sm">{source.authorization_status} · {source.is_active ? "aktif" : "nonaktif"}</p></div>)}</div><form action={registerExternalSource} className="mt-6 grid gap-3"><input name="code" required placeholder="Kode sumber, contoh: SISKOP2MI" className="min-h-11 rounded-lg border px-3"/><input name="name" required placeholder="Nama resmi sumber" className="min-h-11 rounded-lg border px-3"/><input name="officialUrl" type="url" required placeholder="URL resmi HTTPS" className="min-h-11 rounded-lg border px-3"/><input name="adapterKey" required placeholder="Adapter key, contoh: siskop2mi" className="min-h-11 rounded-lg border px-3"/><button className="min-h-11 rounded-lg bg-slate-900 font-semibold text-white">Daftarkan sebagai nonaktif</button></form></section></Container></main>;
}
