import { Container } from "@/components/ui/container";
import { requireOnboardedUser } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { createJobAlert, deleteJobAlert, updateJobAlert } from "../actions";

export default async function AlertsPage() {
  const { user } = await requireOnboardedUser(); const supabase = await createClient();
  const { data } = await supabase.from("job_alerts").select("id,name,keywords,location_text,employment_type,is_active").eq("user_id", user.id).order("created_at", { ascending: false });
  return <main className="flex-1 py-12"><Container><div className="max-w-3xl"><h1 className="text-4xl font-bold">Job alerts</h1><p className="mt-3 text-slate-600">Simpan kriteria pencarian. Pengiriman notifikasi otomatis ditunda sampai infrastruktur resmi tersedia.</p><form action={createJobAlert} className="mt-8 grid gap-4 rounded-2xl border bg-white p-6"><input name="name" required minLength={2} placeholder="Nama alert" className="min-h-11 rounded-lg border px-3"/><input name="keywords" placeholder="Kata kunci" className="min-h-11 rounded-lg border px-3"/><input name="location" placeholder="Lokasi" className="min-h-11 rounded-lg border px-3"/><EmploymentType/><button className="min-h-11 rounded-lg bg-brand-700 font-semibold text-white">Simpan alert</button></form><div className="mt-6 grid gap-3">{data?.map((alert) => <form action={updateJobAlert} key={alert.id} className="grid gap-3 rounded-xl border bg-white p-4"><input type="hidden" name="alertId" value={alert.id}/><input name="name" defaultValue={alert.name} required minLength={2} className="min-h-10 rounded-lg border px-3"/><input name="keywords" defaultValue={alert.keywords ?? ""} placeholder="Kata kunci" className="min-h-10 rounded-lg border px-3"/><input name="location" defaultValue={alert.location_text ?? ""} placeholder="Lokasi" className="min-h-10 rounded-lg border px-3"/><EmploymentType defaultValue={alert.employment_type ?? ""}/><label className="flex gap-2 text-sm"><input type="checkbox" name="isActive" value="yes" defaultChecked={alert.is_active}/>Aktif</label><div className="flex gap-3"><button className="rounded-lg bg-slate-900 px-4 py-2 font-semibold text-white">Perbarui</button><button formAction={deleteJobAlert} className="rounded-lg border px-4 py-2 font-semibold text-red-700">Hapus</button></div></form>)}</div></div></Container></main>;
}

function EmploymentType({ defaultValue = "" }: { defaultValue?: string }) { return <select name="employmentType" defaultValue={defaultValue} className="min-h-11 rounded-lg border px-3"><option value="">Semua jenis</option><option value="full_time">Penuh waktu</option><option value="part_time">Paruh waktu</option><option value="contract">Kontrak</option><option value="temporary">Sementara</option><option value="internship">Magang</option></select>; }
