import Link from "next/link";
import { notFound } from "next/navigation";
import { Container } from "@/components/ui/container";
import { createClient } from "@/lib/supabase/server";
import { applyForJob, saveJob } from "../../actions";

type JobDetail = { id: string; title: string; description: string; location_text: string; employment_type: string; salary_text: string | null; application_url: string | null; source_type: "internal" | "external"; external_id: string | null; original_url: string | null; last_checked_at: string | null; deadline: string | null; employers: { name: string } | null; external_job_sources: { name: string; official_url: string } | null };

export default async function JobDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createClient();
  const { data: job } = await supabase.from("jobs").select("id,title,description,location_text,employment_type,salary_text,application_url,source_type,external_id,original_url,last_checked_at,deadline,employers(name),external_job_sources(name,official_url)").eq("id", id).eq("status", "published").maybeSingle<JobDetail>();
  if (!job) notFound();
  return <main className="flex-1 py-12"><Container><Link href="/career" className="text-sm font-semibold text-brand-700">← Kembali ke pencarian</Link><article className="mt-6 max-w-3xl rounded-2xl border bg-white p-8"><span className="text-xs font-semibold uppercase text-brand-700">{job.source_type === "external" ? "Lowongan eksternal resmi" : "Lowongan internal"}</span><h1 className="mt-3 text-3xl font-bold">{job.title}</h1><p className="mt-3 text-slate-600">{job.employers?.name ?? job.external_job_sources?.name ?? "Sumber resmi"} · {job.location_text}</p><p className="mt-2 text-sm">{job.employment_type.replaceAll("_", " ")}{job.salary_text ? ` · ${job.salary_text}` : ""}</p><div className="mt-6 whitespace-pre-wrap text-slate-700">{job.description}</div><dl className="mt-8 grid gap-2 rounded-xl bg-slate-50 p-4 text-sm"><div><dt className="font-semibold">Batas lamaran</dt><dd>{job.deadline ? new Date(job.deadline).toLocaleString("id-ID") : "Tidak dicantumkan"}</dd></div>{job.source_type === "external" && <><div><dt className="font-semibold">Sumber</dt><dd>{job.external_job_sources?.name}</dd></div><div><dt className="font-semibold">External ID</dt><dd>{job.external_id}</dd></div><div><dt className="font-semibold">Terakhir diperiksa</dt><dd>{job.last_checked_at ? new Date(job.last_checked_at).toLocaleString("id-ID") : "—"}</dd></div></>}</dl>{job.original_url && <a href={job.original_url} rel="noreferrer" target="_blank" className="mt-5 inline-block font-semibold text-brand-700">Buka sumber asli ↗</a>}</article>
    <div className="mt-6 grid max-w-3xl gap-6 md:grid-cols-2"><form action={saveJob} className="rounded-2xl border bg-white p-6"><input type="hidden" name="jobId" value={job.id}/><input type="hidden" name="returnPath" value={`/career/jobs/${job.id}`}/><h2 className="font-bold">Simpan lowongan</h2><p className="mt-2 text-sm text-slate-600">Tersimpan hanya di akun Anda.</p><button className="mt-4 min-h-11 w-full rounded-lg border font-semibold">Simpan</button></form>{job.source_type === "internal" ? <form action={applyForJob} className="rounded-2xl border bg-white p-6"><input type="hidden" name="jobId" value={job.id}/><h2 className="font-bold">Lamar gratis</h2><textarea name="coverNote" rows={4} maxLength={3000} placeholder="Catatan singkat (opsional)" className="mt-3 w-full rounded-lg border p-3"/><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" name="sharePassport" value="yes"/>Bagikan Career Passport saya hanya kepada pemberi kerja ini</label><button className="mt-4 min-h-11 w-full rounded-lg bg-brand-700 font-semibold text-white">Kirim lamaran</button></form> : <div className="rounded-2xl border bg-white p-6"><h2 className="font-bold">Lamaran eksternal</h2><p className="mt-2 text-sm text-slate-600">Gunakan situs sumber resmi. DUTA AI tidak mengirim data Career Passport ke sumber eksternal.</p>{job.original_url && <a href={job.original_url} rel="noreferrer" target="_blank" className="mt-4 inline-block rounded-lg bg-brand-700 px-4 py-3 font-semibold text-white">Lamar di sumber asli ↗</a>}</div>}</div>
    </Container></main>;
}
