import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { ButtonLink } from "@/components/ui/button-link";
import { Container } from "@/components/ui/container";
import { inputClass, labelClass, textareaClass } from "@/components/ui/form-control";
import { createClient } from "@/lib/supabase/server";
import { submitOrganization } from "./actions";

export const metadata = { title: "Organisasi", description: "Temukan organisasi, pengumuman, dan acara komunitas Indonesia di Malaysia." };
export const dynamic = "force-dynamic";

export default async function OrganizationsPage({ searchParams }: { searchParams: Promise<{ q?: string; area?: string; success?: string; error?: string }> }) {
  const params = await searchParams;
  const supabase = await createClient();
  let query = supabase.from("organizations").select("id,slug,name,description,city,state_region,verification_status").eq("country_code", "MY").eq("status", "approved").order("name");
  if (params.q) query = query.ilike("name", `%${params.q.replaceAll("%", "")}%`);
  if (params.area) query = query.or(`city.ilike.%${params.area.replaceAll("%", "")}%,state_region.ilike.%${params.area.replaceAll("%", "")}%`);
  const { data: organizations, error } = await query;
  const filtersActive = Boolean(params.q || params.area);

  return <main className="flex-1 pb-20">
    <section className="border-b border-slate-200 bg-white"><Container className="grid gap-7 py-10 sm:py-14 lg:grid-cols-[1fr_auto] lg:items-end"><div className="max-w-3xl"><Badge tone="community">Jejaring diaspora · Malaysia</Badge><h1 className="mt-4 text-4xl font-bold tracking-tight text-slate-950 sm:text-5xl">Temukan komunitas dan organisasi yang relevan.</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-600">Kenali tujuan, lokasi, status verifikasi, pengumuman, dan acara organisasi Indonesia yang tersedia.</p></div><ButtonLink href="/map" variant="secondary">Temukan tempat komunitas</ButtonLink></Container></section>
    <Container>
      <section aria-labelledby="organization-search" className="rounded-b-2xl border border-t-0 border-slate-200 bg-white p-5 shadow-[var(--shadow-low)] sm:p-7"><h2 id="organization-search" className="text-xl font-bold text-slate-950">Cari organisasi</h2><form className="mt-5 grid gap-4 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><div><label htmlFor="q" className={labelClass}>Nama organisasi</label><input id="q" name="q" defaultValue={params.q} placeholder="Cari nama" className={inputClass} /></div><div><label htmlFor="area" className={labelClass}>Kota atau negeri</label><input id="area" name="area" defaultValue={params.area} placeholder="Contoh: Selangor" className={inputClass} /></div><button className="min-h-11 rounded-xl bg-slate-950 px-6 font-bold text-white hover:bg-slate-800">Cari</button></form>{filtersActive && <Link href="/organizations" className="mt-4 inline-flex min-h-10 items-center text-sm font-bold text-primary hover:underline">Hapus filter</Link>}</section>

      {error ? <section role="alert" className="mt-8 rounded-2xl border border-red-200 bg-red-50 p-6"><h2 className="font-bold text-red-950">Organisasi belum dapat dimuat</h2><p className="mt-2 text-sm text-red-800">Silakan muat ulang halaman.</p></section> : <section aria-labelledby="organization-results" className="mt-10"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-brand-700">Direktori komunitas</p><h2 id="organization-results" className="mt-2 text-2xl font-bold text-slate-950">{filtersActive ? "Hasil pencarian" : "Organisasi yang tersedia"}</h2></div><p className="text-sm font-semibold text-slate-500">{organizations?.length ?? 0} organisasi</p></div><div className="mt-5 grid gap-5 md:grid-cols-2">{organizations?.map((organization) => <article key={organization.id} className="group flex min-h-64 flex-col rounded-2xl border border-slate-200 bg-white p-6 shadow-[var(--shadow-low)]"><Badge tone={organization.verification_status === "verified" ? "verified" : "community"} className="self-start">{organization.verification_status === "verified" ? "Terverifikasi" : "Belum terverifikasi"}</Badge><h3 className="mt-5 text-xl font-bold text-slate-950 group-hover:text-primary"><Link href={`/organizations/${organization.slug}`}>{organization.name}</Link></h3><p className="mt-2 text-sm font-semibold text-slate-500">{organization.city}, {organization.state_region}</p><p className="mt-4 line-clamp-3 text-sm leading-6 text-slate-600">{organization.description}</p><Link href={`/organizations/${organization.slug}`} className="mt-auto border-t border-slate-100 pt-5 text-sm font-bold text-primary">Lihat profil dan kegiatan →</Link></article>)}{!organizations?.length && <div className="md:col-span-2 rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-12 text-center"><h3 className="text-xl font-bold text-slate-950">{filtersActive ? "Tidak ada organisasi yang sesuai" : "Belum ada organisasi yang disetujui"}</h3><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-600">{filtersActive ? "Coba nama atau wilayah lain." : "Organisasi yang dikirim komunitas hanya tampil setelah peninjauan."}</p></div>}</div></section>}

      <section className="mt-12 grid gap-8 rounded-2xl border border-slate-200 bg-white p-6 sm:p-8 lg:grid-cols-[0.7fr_1.3fr]"><div><Badge tone="community">Kontribusi komunitas</Badge><h2 className="mt-4 text-2xl font-bold text-slate-950">Tambahkan organisasi</h2><p className="mt-2 text-sm leading-6 text-slate-600">Kiriman menunggu pemeriksaan dan tidak otomatis terverifikasi atau tampil publik.</p></div><form action={submitOrganization} className="grid gap-4"><Input name="name" label="Nama" /><Input name="slug" label="Tautan singkat" /><label className={labelClass}>Deskripsi<textarea name="description" required minLength={20} className={textareaClass} rows={4} /></label><div className="grid gap-4 sm:grid-cols-2"><Input name="city" label="Kota" /><Input name="state" label="Negeri/wilayah" /></div><Input name="publicEmail" label="Email publik (opsional)" type="email" required={false} /><Input name="website" label="Website HTTPS (opsional)" type="url" required={false} /><button className="min-h-11 rounded-xl bg-primary px-5 font-bold text-white hover:bg-primary-hover">Kirim untuk ditinjau</button></form></section>
    </Container>
  </main>;
}

function Input({ name, label, type = "text", required = true }: { name: string; label: string; type?: string; required?: boolean }) { return <label className={labelClass}>{label}<input name={name} type={type} required={required} className={inputClass} /></label>; }
