import QRCode from "qrcode";
import { Container } from "@/components/ui/container";
import { appUrl } from "@/lib/app-url";
import { requireOrganizationAdmin } from "@/lib/organizations/authorization";
import { approveMember, createAnnouncement, createEvent, createJoinLink } from "./actions";

export default async function OrganizationAdminPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const { supabase } = await requireOrganizationAdmin(id);
  const [organization, members, registrations, links] = await Promise.all([supabase.from("organizations").select("id,name,slug").eq("id", id).single(), supabase.from("organization_memberships").select("id,user_id,status,created_at").eq("organization_id", id).eq("role", "member").order("created_at"), supabase.from("organization_event_registrations").select("event_id,user_id,status,created_at,event:organization_events!inner(title,organization_id)").eq("event.organization_id", id).order("created_at"), supabase.from("organization_join_links").select("token,is_active").eq("organization_id", id).eq("is_active", true).limit(1)]);
  if (!organization.data) return null; const joinUrl = links.data?.[0] ? appUrl(`/join/${links.data[0].token}`) : null; const qr = joinUrl ? await QRCode.toString(joinUrl, { type: "svg", width: 200, margin: 1 }) : null;
  return <main className="flex-1 py-12"><Container><h1 className="text-3xl font-bold">Dashboard {organization.data.name}</h1><p className="mt-2 text-slate-600">Semua tindakan dibatasi hanya untuk organisasi ini.</p>
    <div className="mt-8 grid gap-6 lg:grid-cols-2"><Panel title="Permintaan anggota">{members.data?.map((m) => <form key={m.id} action={approveMember} className="rounded-lg border p-4"><input type="hidden" name="organizationId" value={id} /><input type="hidden" name="membershipId" value={m.id} /><p className="text-sm">Pengguna: {m.user_id}</p><p className="text-sm">Status: {m.status}</p>{m.status === "pending" && <div className="mt-3 flex gap-2"><button name="decision" value="approved" className="rounded bg-emerald-700 px-3 py-2 text-white">Setujui</button><button name="decision" value="rejected" className="rounded border px-3 py-2">Tolak</button></div>}</form>)}</Panel>
    <Panel title="Pengumuman"><form action={createAnnouncement} className="grid gap-3"><input type="hidden" name="organizationId" value={id} /><input name="title" required placeholder="Judul" className="min-h-11 rounded border px-3" /><textarea name="body" required minLength={10} placeholder="Isi pengumuman" className="rounded border p-3" /><label><input type="checkbox" name="publish" value="true" /> Publikasikan sekarang</label><button className="rounded bg-slate-900 px-4 py-2 text-white">Simpan</button></form></Panel>
    <Panel title="Acara"><form action={createEvent} className="grid gap-3"><input type="hidden" name="organizationId" value={id} /><input name="title" required placeholder="Judul acara" className="min-h-11 rounded border px-3" /><textarea name="description" required minLength={10} placeholder="Deskripsi" className="rounded border p-3" /><input name="startsAt" type="datetime-local" required className="min-h-11 rounded border px-3" /><input name="endsAt" type="datetime-local" className="min-h-11 rounded border px-3" /><input name="venueName" placeholder="Nama lokasi atau isi URL online" className="min-h-11 rounded border px-3" /><input name="venueAddress" placeholder="Alamat publik acara" className="min-h-11 rounded border px-3" /><input name="onlineUrl" type="url" placeholder="URL online HTTPS" className="min-h-11 rounded border px-3" /><input name="capacity" type="number" min="1" placeholder="Kapasitas" className="min-h-11 rounded border px-3" /><label><input type="checkbox" name="publish" value="true" /> Publikasikan</label><button className="rounded bg-slate-900 px-4 py-2 text-white">Simpan acara</button></form></Panel>
    <Panel title="Tautan & QR bergabung">{joinUrl && qr ? <><div className="w-fit" dangerouslySetInnerHTML={{ __html: qr }} /><p className="mt-2 break-all text-sm">{joinUrl}</p></> : <form action={createJoinLink}><input type="hidden" name="organizationId" value={id} /><button className="rounded bg-brand-700 px-4 py-2 text-white">Buat tautan bergabung</button></form>}</Panel>
    <Panel title="Pendaftaran acara"><p className="text-sm text-slate-600">Hanya admin organisasi ini yang dapat melihat pendaftar.</p>{registrations.data?.map((r) => <div key={`${r.event_id}-${r.user_id}`} className="mt-2 rounded border p-3 text-sm">{(r.event as unknown as { title: string })?.title} · {r.status} · pengguna {r.user_id}</div>)}</Panel>
    <Panel title="AI Secretary (placeholder)"><p className="text-sm text-slate-600">Antarmuka awal untuk membantu draf pengumuman dan agenda. Belum terhubung ke model AI dan tidak mengirim data apa pun.</p><textarea disabled placeholder="AI Secretary akan tersedia setelah persetujuan integrasi." className="mt-4 w-full rounded border bg-slate-50 p-3" rows={4} /><button disabled className="mt-3 rounded bg-slate-300 px-4 py-2 text-slate-600">Buat draf</button></Panel></div>
  </Container></main>;
}
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border bg-white p-6"><h2 className="mb-4 text-xl font-bold">{title}</h2><div className="grid gap-3">{children}</div></section>; }
