import Link from "next/link";
import { notFound } from "next/navigation";
import { Container } from "@/components/ui/container";
import { createClient } from "@/lib/supabase/server";
import { claimOrganization, joinOrganization, registerEvent } from "../actions";

export const dynamic = "force-dynamic";

export default async function OrganizationPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const supabase = await createClient(); const { data: organization } = await supabase.from("organizations").select("id,slug,name,description,city,state_region,public_email,website_url,verification_status,source_url,last_verified_at").eq("slug", slug).eq("status", "approved").single(); if (!organization) notFound();
  const [announcements, events, joinLinks] = await Promise.all([supabase.from("organization_announcements").select("id,title,body,published_at").eq("organization_id", organization.id).eq("status", "published").order("published_at", { ascending: false }), supabase.from("organization_events").select("id,title,description,starts_at,ends_at,venue_name,venue_address,online_url,capacity").eq("organization_id", organization.id).eq("status", "published").order("starts_at"), supabase.from("organization_join_links").select("token").eq("organization_id", organization.id).eq("is_active", true).limit(1)]);
  const path = `/organizations/${slug}`;
  return <main className="flex-1 py-12"><Container><div className="rounded-2xl border bg-white p-7"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-900">{organization.verification_status === "verified" ? "Organisasi terverifikasi" : "Belum terverifikasi"}</span><h1 className="mt-4 text-4xl font-bold">{organization.name}</h1><p className="mt-2 text-slate-500">{organization.city}, {organization.state_region}</p><p className="mt-5 leading-7 text-slate-600">{organization.description}</p><div className="mt-5 flex flex-wrap gap-4">{organization.website_url && <Link href={organization.website_url} className="font-semibold text-brand-700">Website</Link>}{organization.public_email && <Link href={`mailto:${organization.public_email}`} className="font-semibold text-brand-700">Email</Link>}<Link href={`/organizations/${slug}/share`} className="font-semibold text-brand-700">Bagikan</Link></div></div>
    <div className="mt-6 flex flex-wrap gap-3"><form action={joinOrganization}><input type="hidden" name="organizationId" value={organization.id} /><input type="hidden" name="returnPath" value={path} /><button className="rounded-lg bg-brand-700 px-5 py-3 font-semibold text-white">Ajukan keanggotaan</button></form>{joinLinks.data?.[0] && <Link href={`/join/${joinLinks.data[0].token}`} className="rounded-lg border px-5 py-3 font-semibold">Buka tautan bergabung</Link>}</div>
    <section className="mt-10"><h2 className="text-2xl font-bold">Pengumuman</h2><div className="mt-4 grid gap-4">{announcements.data?.map((a) => <article key={a.id} className="rounded-xl border bg-white p-5"><h3 className="font-bold">{a.title}</h3><p className="mt-2 text-slate-600">{a.body}</p></article>)}{!announcements.data?.length && <p className="text-slate-600">Belum ada pengumuman.</p>}</div></section>
    <section className="mt-10"><h2 className="text-2xl font-bold">Acara</h2><div className="mt-4 grid gap-4">{events.data?.map((e) => <article key={e.id} className="rounded-xl border bg-white p-5"><h3 className="font-bold">{e.title}</h3><p className="mt-2 text-slate-600">{e.description}</p><p className="mt-2 text-sm">{new Date(e.starts_at).toLocaleString("id-ID")} · {e.venue_name ?? "Online"}</p><form action={registerEvent} className="mt-4"><input type="hidden" name="eventId" value={e.id} /><input type="hidden" name="returnPath" value={path} /><button className="rounded-lg bg-slate-900 px-4 py-2 font-semibold text-white">Daftar acara</button></form></article>)}{!events.data?.length && <p className="text-slate-600">Belum ada acara.</p>}</div></section>
    <section className="mt-10 rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Klaim organisasi</h2><p className="mt-2 text-sm text-slate-600">Gunakan jika Anda berwenang mewakili organisasi ini.</p><form action={claimOrganization} className="mt-4 grid gap-4"><input type="hidden" name="organizationId" value={organization.id} /><textarea name="reason" required minLength={20} placeholder="Jelaskan hubungan Anda dengan organisasi" className="rounded-lg border p-3" /><input name="evidenceUrl" type="url" placeholder="URL bukti HTTPS (opsional)" className="min-h-11 rounded-lg border px-3" /><button className="rounded-lg border px-4 py-2 font-semibold">Kirim klaim</button></form></section>
  </Container></main>;
}
